name: third_pipeline
on: 
  schedule:
    - cron: "5 * * * 1-5"
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, Ran Successfully through CRON job"
